spring:
  datasource:
    url: jdbc:mysql://localhost:3306/edu_connect
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
